#!/usr/bin/env bash
#This script dispalys "best School" 9 times then "Hi" and finaly "Best School" again
count=1
while [ $count -le 10 ]; do echo "Best School"; if [ $count -eq 9 ]; then echo "Hi"; fi; ((count++)); done
