#!/usr/bin/env bash
#This script displays "bad luck" on the fourth iteration, "good luck" on the eight and "Best School" on all other iterations
count=1
while [ $count -le 10 ]; do if [ $count -eq 4 ]; then echo "bad luck"; elif [ $count -eq 8 ]; then echo "good luck"; else echo "Best School"; fi; ((count++)); done
